### ISSUE TITLE
Fails due to "stack ghci" not accepting the "--no-build" flag

### ISSUE THREAD

**Issue by purcell** [chrisdone/flycheck-stack#3]
I have the latest `stack`, having just `stack upgrade`-d:

```
% stack --version
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

Do you perhaps use a different version?

**Comment by chrisdone** [comment]
I think 1.0.4.3 is the latest stack release https://github.com/commercialhaskell/stack/releases

**Comment by purcell** [comment]
Indeed, sorry - looks like I was stuck with an outdated version which couldn't upgrade itself fully.
