### ISSUE TITLE
Add documentation regarding interoperability with flycheck-haskell?

### ISSUE THREAD

**Issue by mmaz** [chrisdone/flycheck-stack#4]
Hi Chris, thank you for continuing to spearhead the advancement of the Haskell tooling ecosystem! I am really excited to start using this project, especially with its support for flychecking project-less haskell files via the global `stack` configuration!  I wanted to provide two notes on my first impressions regarding the documentation, from my perspective as a total newcomer, which I hope you'll find valuable:
- After reading the readme I felt uncertain if this supplants [`flycheck-haskell`](https://github.com/flycheck/flycheck-haskell/) which also supports `stack` projects (I believe via [this issue](https://github.com/flycheck/flycheck-haskell/issues/47)). As I am not very familiar with emacs (thanks to the fact that `haskell-mode` mostly "just works" for me!), I feel unclear if `flycheck-stack` or `flycheck-haskell` are complementary or whether they will somehow clash.
- As a `Cask` user, I was happy to note that I could fetch the project from `melpa` but the discoverability of this convenience is a bit obscured - perhaps a melpa badge and a mention at the top of the readme (again, akin to [`flycheck-haskell`](https://github.com/flycheck/flycheck-haskell/blob/master/README.md)) would help advertise this?

**Comment by chrisdone** [comment]
I'm not maintaining this project anymore. It's superseded by [intero](https://github.com/chrisdone/intero).
